baseURL = 'https://guilherme13c.github.io/simple-byte/'
languageCode = 'en-us'
title = 'Simple Byte'
pagination.pagerSize = 10

googleAnalytics = "G-WGBSERX7NC"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[frontmatter]
  date = ['date', 'pubdate', 'lastmod', 'modified']
  expiryDate = ['unpublishdate']
  lastmod = [':git', 'lastmod', 'modified', 'date', 'pubdate']
  publishDate = ['pubdate', 'date']

[params]
  author = "Guilherme Caporali"
  favicon = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'
