baseURL = 'https://guilherme13c.github.io/simple-byte/'
languageCode = 'en-us'
title = 'Simple Byte'
theme = "ananke"
paginate = 10

[params]
  author = "Guilherme Caporali"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
